version: '2'
services:
  mysql:
    image: "mysql:5.7"
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  liquibase:
    image: "goruha/liquibase-mysql:3.4.2"
    network_mode: "host"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=localhost
      - TARGET_DATABASE=email_dev?createDatabaseIfNotExist=true
      - MYSQL_PASSWORD=root
    volumes:
      - /vagrant/liquibase_changelog:/changelogs
